version: '3'
services:
  redis:
    image: "redislabs/redistimeseries:edge"
    ports:
      - "6380:6379"
   command: redis-server --requirepass mypassword --loadmodule /usr/lib/redis/modules/redistimeseries.so
